site_name: threatester
site_url: https://mrtc0.github.io/threatester/
site_description: Threatester is a Kubernetes Operator for testing threat detection.
docs_dir: docs/
repo_name: GitHub
repo_url: https://github.com/mrtc0/threatester

theme:
  name: material
  palette:
    primary: teal
  language: 'en'
  features:
    - navigation.tabs
    - navigation.tabs.sticky

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - footnotes
  - attr_list
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search

nav:
  - HOME: index.md
