apiVersion: threatester.github.io/v1alpha1
kind: Scenario
metadata:
  labels:
    app.kubernetes.io/name: scenario
    app.kubernetes.io/instance: scenario-sample
    app.kubernetes.io/part-of: threatester
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: threatester
  name: scenario-sample
spec:
  # TODO(user): Add fields here
